/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
*/

const difference = function(s,t) {
    s.toLowerCase().replace(/[^A-Za-z0-9]/g, '').split('').sort().join('')
    t.toLowerCase().replace(/[^A-Za-z0-9]/g, '').split('').sort().join('')

    for (const num of t){
        if (!(s.includes(num)))
        {
            return num;
        }
    }


}

const s = "abcd"
const t = "abcde"

const miss = difference(s,t)
console.log(miss)